# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blnpdf <- function(x, size, mean = 0L, sd = 1L) {
    .Call('_bln_blnpdf', PACKAGE = 'bln', x, size, mean, sd)
}

